### ISSUE TITLE
Issue when building SWIG

### ISSUE THREAD

**Issue by laurent101** [OpenSourceRisk/ORE-SWIG#10]
Hi, I've run into the following issue when building ORE SWIG

The build process in Linux fails with the following  error:

/quant/QLibs/ORE1080500/QuantExt/qle/termstructures/kinterpolatedyoyoptionletvolatilitysurface.hpp:118:56: error: cannot convert 'const boost::shared_ptr<QuantExt::YoYInflationCapFloorEngine> to 'const boost::shared_ptr<QuantLib::YoYInflationCapFloorEngine>&'
  118 |     yoyOptionletStripper_->initialize(capFloorPrices_, yoyInflationCouponPricer_, slope_);
      |                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                        |
      |                                                        const boost::shared_ptr<QuantExt::YoYInflationCapFloorEngine>
In file included from /quant/QLibs/ORE1080500/QuantLib/ql/experimental/inflation/interpolatedyoyoptionletstripper.hpp:30,
                 from /quant/QLibs/ORE1080500/QuantLib/ql/experimental/inflation/all.hpp:7,

This is however not a problem when building ORE Engine.

Any thoughts?

Thanks for your assistance.

**Comment by farahkhashman** [comment]
hello, what was your fix for this issue?
