### ISSUE TITLE
qle_calendars.i is not included in qle.i

### ISSUE THREAD

**Issue by eltoder** [OpenSourceRisk/ORE-SWIG#21]
As far as I can tell, qle_calendars.i is not used anywhere, so the calendars are not exposed.

CC @pcaspers

**Comment by pcaspers** [comment]
@eltoder we'll check, thank you!

**Comment by eltoder** [comment]
I also spotted a typo in qle_calendars where Wmr is misspelled as Wr.

**Comment by QuaternionRisk** [comment]
Indeed, that will be be cleaned up and included in the release this month

**Comment by eltoder** [comment]
Looks like this was fixed.
